version: 2
jobs:
  build:
    branches:
      only:
        - dev
        - master
        - ci
    working_directory: ~/circleci/stac-validator
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: v1-python-requirements-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pip install -r requirements.txt
      - save_cache:
          key: v1-python-requirements-{{ checksum "requirements.txt" }}
          paths:
            - "~/.cache/pip"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          command: |
            python -m pytest